<?php
/**
 * OrderRecordResourceApi
 * PHP version 5
 *
 * @category Class
 * @package  passhub\client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassHub API
 *
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace passhub\client\api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use passhub\client\ApiException;
use passhub\client\Configuration;
use passhub\client\HeaderSelector;
use passhub\client\ObjectSerializer;

/**
 * OrderRecordResourceApi Class Doc Comment
 *
 * @category Class
 * @package  passhub\client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderRecordResourceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createOrderRecord
     *
     * createOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \passhub\client\model\OrderRecordDTO
     */
    public function createOrderRecord($order_record_dto)
    {
        list($response) = $this->createOrderRecordWithHttpInfo($order_record_dto);
        return $response;
    }

    /**
     * Operation createOrderRecordWithHttpInfo
     *
     * createOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \passhub\client\model\OrderRecordDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function createOrderRecordWithHttpInfo($order_record_dto)
    {
        $returnType = '\passhub\client\model\OrderRecordDTO';
        $request = $this->createOrderRecordRequest($order_record_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\passhub\client\model\OrderRecordDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createOrderRecordAsync
     *
     * createOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrderRecordAsync($order_record_dto)
    {
        return $this->createOrderRecordAsyncWithHttpInfo($order_record_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createOrderRecordAsyncWithHttpInfo
     *
     * createOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createOrderRecordAsyncWithHttpInfo($order_record_dto)
    {
        $returnType = '\passhub\client\model\OrderRecordDTO';
        $request = $this->createOrderRecordRequest($order_record_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createOrderRecord'
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createOrderRecordRequest($order_record_dto)
    {
        // verify the required parameter 'order_record_dto' is set
        if ($order_record_dto === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_record_dto when calling createOrderRecord'
            );
        }

        $resourcePath = '/api/v1/orderRecords';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($order_record_dto)) {
            $_tempBody = $order_record_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAllOrderRecords
     *
     * getAllOrderRecords
     *
     * @param  string $query query text (optional)
     * @param  string $from Begin the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $till End the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $time_zone A timezone for date/time representation. Example: America/Chicago or EST. If zone is not set, then UTC timezone will be used. (optional)
     * @param  string $delivery_method delivery method (optional)
     * @param  string $delivery_status status of delivery (optional)
     * @param  int $size quantity of listed records on page (optional)
     * @param  int $page listing starts from page value (optional)
     * @param  string $sort_by sort by (optional)
     * @param  string $sort_order sort order (optional)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \passhub\client\model\OrderRecordExtendDTO[]
     */
    public function getAllOrderRecords($query = null, $from = null, $till = null, $time_zone = null, $delivery_method = null, $delivery_status = null, $size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        list($response) = $this->getAllOrderRecordsWithHttpInfo($query, $from, $till, $time_zone, $delivery_method, $delivery_status, $size, $page, $sort_by, $sort_order);
        return $response;
    }

    /**
     * Operation getAllOrderRecordsWithHttpInfo
     *
     * getAllOrderRecords
     *
     * @param  string $query query text (optional)
     * @param  string $from Begin the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $till End the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $time_zone A timezone for date/time representation. Example: America/Chicago or EST. If zone is not set, then UTC timezone will be used. (optional)
     * @param  string $delivery_method delivery method (optional)
     * @param  string $delivery_status status of delivery (optional)
     * @param  int $size quantity of listed records on page (optional)
     * @param  int $page listing starts from page value (optional)
     * @param  string $sort_by sort by (optional)
     * @param  string $sort_order sort order (optional)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \passhub\client\model\OrderRecordExtendDTO[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getAllOrderRecordsWithHttpInfo($query = null, $from = null, $till = null, $time_zone = null, $delivery_method = null, $delivery_status = null, $size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        $returnType = '\passhub\client\model\OrderRecordExtendDTO[]';
        $request = $this->getAllOrderRecordsRequest($query, $from, $till, $time_zone, $delivery_method, $delivery_status, $size, $page, $sort_by, $sort_order);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\passhub\client\model\OrderRecordExtendDTO[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAllOrderRecordsAsync
     *
     * getAllOrderRecords
     *
     * @param  string $query query text (optional)
     * @param  string $from Begin the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $till End the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $time_zone A timezone for date/time representation. Example: America/Chicago or EST. If zone is not set, then UTC timezone will be used. (optional)
     * @param  string $delivery_method delivery method (optional)
     * @param  string $delivery_status status of delivery (optional)
     * @param  int $size quantity of listed records on page (optional)
     * @param  int $page listing starts from page value (optional)
     * @param  string $sort_by sort by (optional)
     * @param  string $sort_order sort order (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllOrderRecordsAsync($query = null, $from = null, $till = null, $time_zone = null, $delivery_method = null, $delivery_status = null, $size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        return $this->getAllOrderRecordsAsyncWithHttpInfo($query, $from, $till, $time_zone, $delivery_method, $delivery_status, $size, $page, $sort_by, $sort_order)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAllOrderRecordsAsyncWithHttpInfo
     *
     * getAllOrderRecords
     *
     * @param  string $query query text (optional)
     * @param  string $from Begin the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $till End the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $time_zone A timezone for date/time representation. Example: America/Chicago or EST. If zone is not set, then UTC timezone will be used. (optional)
     * @param  string $delivery_method delivery method (optional)
     * @param  string $delivery_status status of delivery (optional)
     * @param  int $size quantity of listed records on page (optional)
     * @param  int $page listing starts from page value (optional)
     * @param  string $sort_by sort by (optional)
     * @param  string $sort_order sort order (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAllOrderRecordsAsyncWithHttpInfo($query = null, $from = null, $till = null, $time_zone = null, $delivery_method = null, $delivery_status = null, $size = null, $page = null, $sort_by = null, $sort_order = null)
    {
        $returnType = '\passhub\client\model\OrderRecordExtendDTO[]';
        $request = $this->getAllOrderRecordsRequest($query, $from, $till, $time_zone, $delivery_method, $delivery_status, $size, $page, $sort_by, $sort_order);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAllOrderRecords'
     *
     * @param  string $query query text (optional)
     * @param  string $from Begin the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $till End the of date range, format: YYYY-MM-DD (e.g. 2016-01-25) (optional)
     * @param  string $time_zone A timezone for date/time representation. Example: America/Chicago or EST. If zone is not set, then UTC timezone will be used. (optional)
     * @param  string $delivery_method delivery method (optional)
     * @param  string $delivery_status status of delivery (optional)
     * @param  int $size quantity of listed records on page (optional)
     * @param  int $page listing starts from page value (optional)
     * @param  string $sort_by sort by (optional)
     * @param  string $sort_order sort order (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getAllOrderRecordsRequest($query = null, $from = null, $till = null, $time_zone = null, $delivery_method = null, $delivery_status = null, $size = null, $page = null, $sort_by = null, $sort_order = null)
    {

        $resourcePath = '/api/v2/orderRecords';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($query !== null) {
            $queryParams['query'] = ObjectSerializer::toQueryValue($query);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($till !== null) {
            $queryParams['till'] = ObjectSerializer::toQueryValue($till);
        }
        // query params
        if ($time_zone !== null) {
            $queryParams['timeZone'] = ObjectSerializer::toQueryValue($time_zone);
        }
        // query params
        if ($delivery_method !== null) {
            $queryParams['deliveryMethod'] = ObjectSerializer::toQueryValue($delivery_method);
        }
        // query params
        if ($delivery_status !== null) {
            $queryParams['deliveryStatus'] = ObjectSerializer::toQueryValue($delivery_status);
        }
        // query params
        if ($size !== null) {
            $queryParams['size'] = ObjectSerializer::toQueryValue($size);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }
        // query params
        if ($sort_order !== null) {
            $queryParams['sortOrder'] = ObjectSerializer::toQueryValue($sort_order);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOrderRecord
     *
     * getOrderRecord
     *
     * @param  int $id the internal id of order (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \passhub\client\model\OrderRecordExtendDTO
     */
    public function getOrderRecord($id)
    {
        list($response) = $this->getOrderRecordWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getOrderRecordWithHttpInfo
     *
     * getOrderRecord
     *
     * @param  int $id the internal id of order (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \passhub\client\model\OrderRecordExtendDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrderRecordWithHttpInfo($id)
    {
        $returnType = '\passhub\client\model\OrderRecordExtendDTO';
        $request = $this->getOrderRecordRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\passhub\client\model\OrderRecordExtendDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOrderRecordAsync
     *
     * getOrderRecord
     *
     * @param  int $id the internal id of order (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderRecordAsync($id)
    {
        return $this->getOrderRecordAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrderRecordAsyncWithHttpInfo
     *
     * getOrderRecord
     *
     * @param  int $id the internal id of order (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrderRecordAsyncWithHttpInfo($id)
    {
        $returnType = '\passhub\client\model\OrderRecordExtendDTO';
        $request = $this->getOrderRecordRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrderRecord'
     *
     * @param  int $id the internal id of order (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getOrderRecordRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getOrderRecord'
            );
        }

        $resourcePath = '/api/v1/orderRecords/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation mergeVouchers
     *
     * mergeVouchers
     *
     * @param  int $order_id the internal id of order (required)
     * @param  string $new_voucher_id newVoucherId (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \passhub\client\model\GenericStatusDTO
     */
    public function mergeVouchers($order_id, $new_voucher_id)
    {
        list($response) = $this->mergeVouchersWithHttpInfo($order_id, $new_voucher_id);
        return $response;
    }

    /**
     * Operation mergeVouchersWithHttpInfo
     *
     * mergeVouchers
     *
     * @param  int $order_id the internal id of order (required)
     * @param  string $new_voucher_id newVoucherId (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \passhub\client\model\GenericStatusDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function mergeVouchersWithHttpInfo($order_id, $new_voucher_id)
    {
        $returnType = '\passhub\client\model\GenericStatusDTO';
        $request = $this->mergeVouchersRequest($order_id, $new_voucher_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\passhub\client\model\GenericStatusDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation mergeVouchersAsync
     *
     * mergeVouchers
     *
     * @param  int $order_id the internal id of order (required)
     * @param  string $new_voucher_id newVoucherId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mergeVouchersAsync($order_id, $new_voucher_id)
    {
        return $this->mergeVouchersAsyncWithHttpInfo($order_id, $new_voucher_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation mergeVouchersAsyncWithHttpInfo
     *
     * mergeVouchers
     *
     * @param  int $order_id the internal id of order (required)
     * @param  string $new_voucher_id newVoucherId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function mergeVouchersAsyncWithHttpInfo($order_id, $new_voucher_id)
    {
        $returnType = '\passhub\client\model\GenericStatusDTO';
        $request = $this->mergeVouchersRequest($order_id, $new_voucher_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'mergeVouchers'
     *
     * @param  int $order_id the internal id of order (required)
     * @param  string $new_voucher_id newVoucherId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function mergeVouchersRequest($order_id, $new_voucher_id)
    {
        // verify the required parameter 'order_id' is set
        if ($order_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_id when calling mergeVouchers'
            );
        }
        // verify the required parameter 'new_voucher_id' is set
        if ($new_voucher_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $new_voucher_id when calling mergeVouchers'
            );
        }

        $resourcePath = '/api/v1/orderRecords/mergeVouchers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($order_id !== null) {
            $queryParams['orderId'] = ObjectSerializer::toQueryValue($order_id);
        }
        // query params
        if ($new_voucher_id !== null) {
            $queryParams['newVoucherId'] = ObjectSerializer::toQueryValue($new_voucher_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateOrderRecord
     *
     * updateOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \passhub\client\model\OrderRecordDTO
     */
    public function updateOrderRecord($order_record_dto)
    {
        list($response) = $this->updateOrderRecordWithHttpInfo($order_record_dto);
        return $response;
    }

    /**
     * Operation updateOrderRecordWithHttpInfo
     *
     * updateOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \passhub\client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \passhub\client\model\OrderRecordDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateOrderRecordWithHttpInfo($order_record_dto)
    {
        $returnType = '\passhub\client\model\OrderRecordDTO';
        $request = $this->updateOrderRecordRequest($order_record_dto);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\passhub\client\model\OrderRecordDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateOrderRecordAsync
     *
     * updateOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrderRecordAsync($order_record_dto)
    {
        return $this->updateOrderRecordAsyncWithHttpInfo($order_record_dto)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateOrderRecordAsyncWithHttpInfo
     *
     * updateOrderRecord
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateOrderRecordAsyncWithHttpInfo($order_record_dto)
    {
        $returnType = '\passhub\client\model\OrderRecordDTO';
        $request = $this->updateOrderRecordRequest($order_record_dto);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateOrderRecord'
     *
     * @param  \passhub\client\model\OrderRecordDTO $order_record_dto the OrderRecord Dto (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function updateOrderRecordRequest($order_record_dto)
    {
        // verify the required parameter 'order_record_dto' is set
        if ($order_record_dto === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_record_dto when calling updateOrderRecord'
            );
        }

        $resourcePath = '/api/v1/orderRecords';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($order_record_dto)) {
            $_tempBody = $order_record_dto;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
