<?php
/**
 * ProductDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  passhub\client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PassHub API
 *
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace passhub\client\model;

use \ArrayAccess;
use \passhub\client\ObjectSerializer;

/**
 * ProductDTO Class Doc Comment
 *
 * @category Class
 * @package  passhub\client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProductDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'allow_recharge' => 'bool',
        'customer_type' => 'string',
        'id' => 'int',
        'name' => 'string',
        'package_product_id' => 'string',
        'price' => 'double',
        'product_id' => 'string',
        'recharge_price' => 'double',
        'retail_price' => 'double',
        'sku' => 'string',
        'sub_product_id' => 'string',
        'tags' => 'string[]',
        'timezone' => 'string',
        'type' => 'string',
        'valid_value' => 'int',
        'validation_tag' => 'string',
        'vendor_account_id' => 'string',
        'vendor_name' => 'string',
        'vendor_sku' => 'string',
        'voucher_pattern' => '\passhub\client\model\VoucherPattern',
        'voucher_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'allow_recharge' => null,
        'customer_type' => null,
        'id' => 'int64',
        'name' => null,
        'package_product_id' => null,
        'price' => 'double',
        'product_id' => null,
        'recharge_price' => 'double',
        'retail_price' => 'double',
        'sku' => null,
        'sub_product_id' => null,
        'tags' => null,
        'timezone' => null,
        'type' => null,
        'valid_value' => 'int32',
        'validation_tag' => null,
        'vendor_account_id' => null,
        'vendor_name' => null,
        'vendor_sku' => null,
        'voucher_pattern' => null,
        'voucher_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allow_recharge' => 'allowRecharge',
        'customer_type' => 'customerType',
        'id' => 'id',
        'name' => 'name',
        'package_product_id' => 'packageProductId',
        'price' => 'price',
        'product_id' => 'productId',
        'recharge_price' => 'rechargePrice',
        'retail_price' => 'retailPrice',
        'sku' => 'sku',
        'sub_product_id' => 'subProductId',
        'tags' => 'tags',
        'timezone' => 'timezone',
        'type' => 'type',
        'valid_value' => 'validValue',
        'validation_tag' => 'validationTag',
        'vendor_account_id' => 'vendorAccountId',
        'vendor_name' => 'vendorName',
        'vendor_sku' => 'vendorSku',
        'voucher_pattern' => 'voucherPattern',
        'voucher_type' => 'voucherType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allow_recharge' => 'setAllowRecharge',
        'customer_type' => 'setCustomerType',
        'id' => 'setId',
        'name' => 'setName',
        'package_product_id' => 'setPackageProductId',
        'price' => 'setPrice',
        'product_id' => 'setProductId',
        'recharge_price' => 'setRechargePrice',
        'retail_price' => 'setRetailPrice',
        'sku' => 'setSku',
        'sub_product_id' => 'setSubProductId',
        'tags' => 'setTags',
        'timezone' => 'setTimezone',
        'type' => 'setType',
        'valid_value' => 'setValidValue',
        'validation_tag' => 'setValidationTag',
        'vendor_account_id' => 'setVendorAccountId',
        'vendor_name' => 'setVendorName',
        'vendor_sku' => 'setVendorSku',
        'voucher_pattern' => 'setVoucherPattern',
        'voucher_type' => 'setVoucherType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allow_recharge' => 'getAllowRecharge',
        'customer_type' => 'getCustomerType',
        'id' => 'getId',
        'name' => 'getName',
        'package_product_id' => 'getPackageProductId',
        'price' => 'getPrice',
        'product_id' => 'getProductId',
        'recharge_price' => 'getRechargePrice',
        'retail_price' => 'getRetailPrice',
        'sku' => 'getSku',
        'sub_product_id' => 'getSubProductId',
        'tags' => 'getTags',
        'timezone' => 'getTimezone',
        'type' => 'getType',
        'valid_value' => 'getValidValue',
        'validation_tag' => 'getValidationTag',
        'vendor_account_id' => 'getVendorAccountId',
        'vendor_name' => 'getVendorName',
        'vendor_sku' => 'getVendorSku',
        'voucher_pattern' => 'getVoucherPattern',
        'voucher_type' => 'getVoucherType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CUSTOMER_TYPE_ADULT = 'ADULT';
    const CUSTOMER_TYPE_CHILD = 'CHILD';
    const CUSTOMER_TYPE_SENIOR = 'SENIOR';
    const TYPE_BASIC_SINGLE = 'BASIC_SINGLE';
    const TYPE_BASIC_VALID_HOURS = 'BASIC_VALID_HOURS';
    const TYPE_PASS_LIMITED = 'PASS_LIMITED';
    const TYPE_PASS_UNLIMITED = 'PASS_UNLIMITED';
    const TYPE_PASS_CALENDAR = 'PASS_CALENDAR';
    const TYPE_FLEXPASS = 'FLEXPASS';
    const TYPE_PASS_CURRENCY = 'PASS_CURRENCY';
    const VOUCHER_TYPE__DEFAULT = 'DEFAULT';
    const VOUCHER_TYPE_CUSTOM = 'CUSTOM';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCustomerTypeAllowableValues()
    {
        return [
            self::CUSTOMER_TYPE_ADULT,
            self::CUSTOMER_TYPE_CHILD,
            self::CUSTOMER_TYPE_SENIOR,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_BASIC_SINGLE,
            self::TYPE_BASIC_VALID_HOURS,
            self::TYPE_PASS_LIMITED,
            self::TYPE_PASS_UNLIMITED,
            self::TYPE_PASS_CALENDAR,
            self::TYPE_FLEXPASS,
            self::TYPE_PASS_CURRENCY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVoucherTypeAllowableValues()
    {
        return [
            self::VOUCHER_TYPE__DEFAULT,
            self::VOUCHER_TYPE_CUSTOM,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['allow_recharge'] = isset($data['allow_recharge']) ? $data['allow_recharge'] : null;
        $this->container['customer_type'] = isset($data['customer_type']) ? $data['customer_type'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['package_product_id'] = isset($data['package_product_id']) ? $data['package_product_id'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['product_id'] = isset($data['product_id']) ? $data['product_id'] : null;
        $this->container['recharge_price'] = isset($data['recharge_price']) ? $data['recharge_price'] : null;
        $this->container['retail_price'] = isset($data['retail_price']) ? $data['retail_price'] : null;
        $this->container['sku'] = isset($data['sku']) ? $data['sku'] : null;
        $this->container['sub_product_id'] = isset($data['sub_product_id']) ? $data['sub_product_id'] : null;
        $this->container['tags'] = isset($data['tags']) ? $data['tags'] : null;
        $this->container['timezone'] = isset($data['timezone']) ? $data['timezone'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['valid_value'] = isset($data['valid_value']) ? $data['valid_value'] : null;
        $this->container['validation_tag'] = isset($data['validation_tag']) ? $data['validation_tag'] : null;
        $this->container['vendor_account_id'] = isset($data['vendor_account_id']) ? $data['vendor_account_id'] : null;
        $this->container['vendor_name'] = isset($data['vendor_name']) ? $data['vendor_name'] : null;
        $this->container['vendor_sku'] = isset($data['vendor_sku']) ? $data['vendor_sku'] : null;
        $this->container['voucher_pattern'] = isset($data['voucher_pattern']) ? $data['voucher_pattern'] : null;
        $this->container['voucher_type'] = isset($data['voucher_type']) ? $data['voucher_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCustomerTypeAllowableValues();
        if (!in_array($this->container['customer_type'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'customer_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getVoucherTypeAllowableValues();
        if (!in_array($this->container['voucher_type'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'voucher_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getCustomerTypeAllowableValues();
        if (!in_array($this->container['customer_type'], $allowedValues)) {
            return false;
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($this->container['type'], $allowedValues)) {
            return false;
        }
        $allowedValues = $this->getVoucherTypeAllowableValues();
        if (!in_array($this->container['voucher_type'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets allow_recharge
     *
     * @return bool
     */
    public function getAllowRecharge()
    {
        return $this->container['allow_recharge'];
    }

    /**
     * Sets allow_recharge
     *
     * @param bool $allow_recharge allow_recharge
     *
     * @return $this
     */
    public function setAllowRecharge($allow_recharge)
    {
        $this->container['allow_recharge'] = $allow_recharge;

        return $this;
    }

    /**
     * Gets customer_type
     *
     * @return string
     */
    public function getCustomerType()
    {
        return $this->container['customer_type'];
    }

    /**
     * Sets customer_type
     *
     * @param string $customer_type customer_type
     *
     * @return $this
     */
    public function setCustomerType($customer_type)
    {
        $allowedValues = $this->getCustomerTypeAllowableValues();
        if (!is_null($customer_type) && !in_array($customer_type, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'customer_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['customer_type'] = $customer_type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets package_product_id
     *
     * @return string
     */
    public function getPackageProductId()
    {
        return $this->container['package_product_id'];
    }

    /**
     * Sets package_product_id
     *
     * @param string $package_product_id package_product_id
     *
     * @return $this
     */
    public function setPackageProductId($package_product_id)
    {
        $this->container['package_product_id'] = $package_product_id;

        return $this;
    }

    /**
     * Gets price
     *
     * @return double
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param double $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets recharge_price
     *
     * @return double
     */
    public function getRechargePrice()
    {
        return $this->container['recharge_price'];
    }

    /**
     * Sets recharge_price
     *
     * @param double $recharge_price recharge_price
     *
     * @return $this
     */
    public function setRechargePrice($recharge_price)
    {
        $this->container['recharge_price'] = $recharge_price;

        return $this;
    }

    /**
     * Gets retail_price
     *
     * @return double
     */
    public function getRetailPrice()
    {
        return $this->container['retail_price'];
    }

    /**
     * Sets retail_price
     *
     * @param double $retail_price retail_price
     *
     * @return $this
     */
    public function setRetailPrice($retail_price)
    {
        $this->container['retail_price'] = $retail_price;

        return $this;
    }

    /**
     * Gets sku
     *
     * @return string
     */
    public function getSku()
    {
        return $this->container['sku'];
    }

    /**
     * Sets sku
     *
     * @param string $sku sku
     *
     * @return $this
     */
    public function setSku($sku)
    {
        $this->container['sku'] = $sku;

        return $this;
    }

    /**
     * Gets sub_product_id
     *
     * @return string
     */
    public function getSubProductId()
    {
        return $this->container['sub_product_id'];
    }

    /**
     * Sets sub_product_id
     *
     * @param string $sub_product_id sub_product_id
     *
     * @return $this
     */
    public function setSubProductId($sub_product_id)
    {
        $this->container['sub_product_id'] = $sub_product_id;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[] $tags tags
     *
     * @return $this
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string $timezone timezone
     *
     * @return $this
     */
    public function setTimezone($timezone)
    {
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets valid_value
     *
     * @return int
     */
    public function getValidValue()
    {
        return $this->container['valid_value'];
    }

    /**
     * Sets valid_value
     *
     * @param int $valid_value valid_value
     *
     * @return $this
     */
    public function setValidValue($valid_value)
    {
        $this->container['valid_value'] = $valid_value;

        return $this;
    }

    /**
     * Gets validation_tag
     *
     * @return string
     */
    public function getValidationTag()
    {
        return $this->container['validation_tag'];
    }

    /**
     * Sets validation_tag
     *
     * @param string $validation_tag validation_tag
     *
     * @return $this
     */
    public function setValidationTag($validation_tag)
    {
        $this->container['validation_tag'] = $validation_tag;

        return $this;
    }

    /**
     * Gets vendor_account_id
     *
     * @return string
     */
    public function getVendorAccountId()
    {
        return $this->container['vendor_account_id'];
    }

    /**
     * Sets vendor_account_id
     *
     * @param string $vendor_account_id vendor_account_id
     *
     * @return $this
     */
    public function setVendorAccountId($vendor_account_id)
    {
        $this->container['vendor_account_id'] = $vendor_account_id;

        return $this;
    }

    /**
     * Gets vendor_name
     *
     * @return string
     */
    public function getVendorName()
    {
        return $this->container['vendor_name'];
    }

    /**
     * Sets vendor_name
     *
     * @param string $vendor_name vendor_name
     *
     * @return $this
     */
    public function setVendorName($vendor_name)
    {
        $this->container['vendor_name'] = $vendor_name;

        return $this;
    }

    /**
     * Gets vendor_sku
     *
     * @return string
     */
    public function getVendorSku()
    {
        return $this->container['vendor_sku'];
    }

    /**
     * Sets vendor_sku
     *
     * @param string $vendor_sku vendor_sku
     *
     * @return $this
     */
    public function setVendorSku($vendor_sku)
    {
        $this->container['vendor_sku'] = $vendor_sku;

        return $this;
    }

    /**
     * Gets voucher_pattern
     *
     * @return \passhub\client\model\VoucherPattern
     */
    public function getVoucherPattern()
    {
        return $this->container['voucher_pattern'];
    }

    /**
     * Sets voucher_pattern
     *
     * @param \passhub\client\model\VoucherPattern $voucher_pattern voucher_pattern
     *
     * @return $this
     */
    public function setVoucherPattern($voucher_pattern)
    {
        $this->container['voucher_pattern'] = $voucher_pattern;

        return $this;
    }

    /**
     * Gets voucher_type
     *
     * @return string
     */
    public function getVoucherType()
    {
        return $this->container['voucher_type'];
    }

    /**
     * Sets voucher_type
     *
     * @param string $voucher_type voucher_type
     *
     * @return $this
     */
    public function setVoucherType($voucher_type)
    {
        $allowedValues = $this->getVoucherTypeAllowableValues();
        if (!is_null($voucher_type) && !in_array($voucher_type, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'voucher_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['voucher_type'] = $voucher_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


